### ISSUE TITLE
New loginless tool in Web Pages category

### ISSUE THREAD

**Issue by NazzarenoG** [fiatjaf/awesome-loginless#1]
I'd add our www.beefree.io
Allows you to create a 100% compatible email template without any signup. Create and export your html

**Comment by fiatjaf** [comment]
I'm not sure what to do with this, because it doesn't seem to fit, although it fits in every possible way.

My idea here was to include stuff that generally needs a login, but these guys made it work without a login -- that definition excludes beefree, I guess, or maybe not. It's not a good definition of what I'm curating here, and it probably excludes some of the content I do have here, but I can't give you none better.

That's to say I'm not sure Beefree fits here, even though it looks really awesome.

I think I'll add it and see what happens.
